/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CausasRouteImport } from './routes/causas'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MigracionRouteImport } from './routes/migracion'
import { Route as RegionalesRouteImport } from './routes/regionales'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as ServiciosRouteImport } from './routes/servicios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CausasRoute = CausasRouteImport.update({
  id: '/causas',
  path: '/causas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MigracionRoute = MigracionRouteImport.update({
  id: '/migracion',
  path: '/migracion',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionalesRoute = RegionalesRouteImport.update({
  id: '/regionales',
  path: '/regionales',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/causas': typeof CausasRoute
  '/dashboard': typeof DashboardRoute
  '/migracion': typeof MigracionRoute
  '/regionales': typeof RegionalesRoute
  '/reportes': typeof ReportesRoute
  '/servicios': typeof ServiciosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/causas': typeof CausasRoute
  '/dashboard': typeof DashboardRoute
  '/migracion': typeof MigracionRoute
  '/regionales': typeof RegionalesRoute
  '/reportes': typeof ReportesRoute
  '/servicios': typeof ServiciosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/causas': typeof CausasRoute
  '/dashboard': typeof DashboardRoute
  '/migracion': typeof MigracionRoute
  '/regionales': typeof RegionalesRoute
  '/reportes': typeof ReportesRoute
  '/servicios': typeof ServiciosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/causas'
    | '/dashboard'
    | '/migracion'
    | '/regionales'
    | '/reportes'
    | '/servicios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/causas'
    | '/dashboard'
    | '/migracion'
    | '/regionales'
    | '/reportes'
    | '/servicios'
  id:
    | '__root__'
    | '/'
    | '/causas'
    | '/dashboard'
    | '/migracion'
    | '/regionales'
    | '/reportes'
    | '/servicios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CausasRoute: typeof CausasRoute
  DashboardRoute: typeof DashboardRoute
  MigracionRoute: typeof MigracionRoute
  RegionalesRoute: typeof RegionalesRoute
  ReportesRoute: typeof ReportesRoute
  ServiciosRoute: typeof ServiciosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/causas': {
      id: '/causas'
      path: '/causas'
      fullPath: '/causas'
      preLoaderRoute: typeof CausasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migracion': {
      id: '/migracion'
      path: '/migracion'
      fullPath: '/migracion'
      preLoaderRoute: typeof MigracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regionales': {
      id: '/regionales'
      path: '/regionales'
      fullPath: '/regionales'
      preLoaderRoute: typeof RegionalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CausasRoute: CausasRoute,
  DashboardRoute: DashboardRoute,
  MigracionRoute: MigracionRoute,
  RegionalesRoute: RegionalesRoute,
  ReportesRoute: ReportesRoute,
  ServiciosRoute: ServiciosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
